name: 'terraform-config-builder'
description:
  'Action to generate terraform config file with provider and state config'
author: 'nuberu'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  mode:
    description: 'How compare with main branch'
    required: true
  organization:
    description: 'Company name'
    required: true
  environment:
    description: 'environment where the changes are applied'
    required: true
# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
